name: "Close stale issues"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue appears to be stale. We’ll automatically close it in a day if there are no further comments.'
        stale-pr-message: 'This PR appears to be stale. We’ll automatically close it in a day if there are no further comments.'
        days-before-stale: 1
        days-before-close: 1
